// ============================================================================
// enterprise_assurance.js — pages enterprise procurement teams demand
// before they sign:
//   - /trust            — security posture + compliance certs (SOC 2,
//                          HIPAA, GDPR, ISO 27001, PCI scope)
//   - /sla              — formal SLAs per tier (uptime % + response time
//                          targets + remedy schedule)
//   - /security/disclosure  — responsible disclosure policy + PGP key
//   - /v1/me/invoices   — list billing invoices for the agent's org
//   - /v1/me/billing/usage  — current period usage broken down for charts
// ============================================================================
const crypto = require('crypto');

async function migrate(pool) {}

async function resolveAgent(pool, req) {
  try { return await require('./me_endpoints').resolveAgentFromRequest(pool, req); }
  catch { return null; }
}

function escapeHtml(s) {
  return String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
}

function renderTrustPage() {
  return `<!doctype html><html><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Trust Center — OpenHeab</title>
<meta name="description" content="OpenHeab security posture, compliance certifications, data handling practices, and audit reports.">
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Inter', sans-serif; background: #0a0a0f; color: #e7e7ee; line-height: 1.6; }
.wrap { max-width: 880px; margin: 0 auto; padding: 48px 24px 80px; }
.nav { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; }
.nav .logo { font-weight: 700; font-size: 18px; color: #fff; text-decoration: none; }
.nav .links a { color: #888; margin-left: 20px; font-size: 14px; text-decoration: none; }
.nav .links a:hover { color: #fff; }
h1 { font-size: 40px; font-weight: 700; letter-spacing: -1px; margin-bottom: 10px; }
.subtitle { color: #888; font-size: 16px; margin-bottom: 36px; max-width: 720px; }
.cert-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 12px; margin-bottom: 40px; }
.cert { background: #14141c; border: 1px solid #1f1f2a; padding: 18px 20px; border-radius: 10px; }
.cert .name { font-weight: 600; font-size: 15px; color: #fff; margin-bottom: 6px; }
.cert .status { font-size: 11px; padding: 3px 8px; border-radius: 100px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; display: inline-block; margin-bottom: 8px; }
.cert .status.live { background: #22c55e20; color: #22c55e; }
.cert .status.progress { background: #eab30820; color: #eab308; }
.cert .status.planned { background: #44445520; color: #888; }
.cert p { font-size: 12px; color: #aaa; line-height: 1.5; }
section { margin: 36px 0; }
section h2 { font-size: 13px; color: #818cf8; text-transform: uppercase; letter-spacing: 1.2px; margin-bottom: 16px; font-weight: 600; }
.fact { background: #14141c; border-left: 3px solid #4f46e5; padding: 14px 20px; border-radius: 4px; margin-bottom: 8px; font-size: 14px; color: #c5c5d5; }
.fact b { color: #fff; }
table { width: 100%; border-collapse: collapse; background: #14141c; border-radius: 10px; overflow: hidden; }
th, td { padding: 12px 16px; text-align: left; font-size: 14px; border-bottom: 1px solid #1f1f2a; }
th { background: #1a1a25; color: #888; font-weight: 500; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
.footer { color: #555; font-size: 13px; margin-top: 48px; text-align: center; }
.footer a { color: #888; margin: 0 8px; }
.callout { background: #181822; border: 1px solid #2a2a36; padding: 20px 24px; border-radius: 10px; margin-bottom: 24px; }
.callout b { color: #fff; }
.actions { display: flex; gap: 10px; margin-top: 16px; flex-wrap: wrap; }
.actions a { padding: 10px 18px; background: #4f46e5; color: #fff; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 13px; }
.actions a.secondary { background: #1a1a25; border: 1px solid #25253a; }
</style></head><body><div class="wrap">

<nav class="nav">
  <a class="logo" href="/">OpenHeab</a>
  <div class="links">
    <a href="/trust" style="color:#fff">Trust</a>
    <a href="/sla">SLA</a>
    <a href="/security/disclosure">Disclosure</a>
    <a href="/legal/privacy">Privacy</a>
    <a href="/pricing">Pricing</a>
  </div>
</nav>

<h1>Trust Center</h1>
<p class="subtitle">How we keep your agents, your money, and your audit trail safe. Updated continuously — every claim below maps to a check in our compliance engine.</p>

<div class="callout">
  <b>Real-time evidence:</b> our compliance posture is generated by <code>audit_core</code> and signed with Ed25519. External auditors get token-scoped access at <code>/audit-portal</code>. Procurement teams: request an SOC 2 report at <a href="mailto:security@openheab.com" style="color:#818cf8">security@openheab.com</a>.
</div>

<section>
  <h2>Certifications</h2>
  <div class="cert-grid">
    <div class="cert">
      <span class="status live">In progress</span>
      <div class="name">SOC 2 Type II</div>
      <p>Continuous controls via audit_core. Type II report expected Q3 2026 from a Big Four auditor.</p>
    </div>
    <div class="cert">
      <span class="status live">In progress</span>
      <div class="name">ISO 27001</div>
      <p>Information Security Management System. Mapping controls in compliance_pack primitive.</p>
    </div>
    <div class="cert">
      <span class="status live">Compliant</span>
      <div class="name">GDPR (EU)</div>
      <p>Self-serve <a href="/v1/legal/gdpr/export" style="color:#818cf8">data export</a> + <a href="/v1/legal/gdpr/delete" style="color:#818cf8">deletion</a>. Articles 15-22.</p>
    </div>
    <div class="cert">
      <span class="status live">Compliant</span>
      <div class="name">CCPA (California)</div>
      <p>Same self-serve mechanism. Verbal/email + API request paths.</p>
    </div>
    <div class="cert">
      <span class="status progress">In progress</span>
      <div class="name">HIPAA</div>
      <p>BAAs available on Enterprise tier. PHI handling in healthcare vertical primitive.</p>
    </div>
    <div class="cert">
      <span class="status progress">In progress</span>
      <div class="name">PCI DSS</div>
      <p>Card PANs encrypted (AES-256-GCM, per-tenant KEKs) in card_core. SAQ-D scope.</p>
    </div>
    <div class="cert">
      <span class="status planned">Q4 2026</span>
      <div class="name">FedRAMP Moderate</div>
      <p>Government tier (verticals/government). Working with sponsor agency.</p>
    </div>
    <div class="cert">
      <span class="status live">Live</span>
      <div class="name">FATF Travel Rule</div>
      <p>Transactions ≥$1000 carry originator+beneficiary info. kyc_advanced primitive.</p>
    </div>
  </div>
</section>

<section>
  <h2>Cryptography + data handling</h2>
  <div class="fact"><b>Encryption at rest:</b> AES-256-GCM with HKDF-derived per-tenant KEKs. Card PANs, private keys, secrets all encrypted before insert. Master keys never leave the OS keyring.</div>
  <div class="fact"><b>Encryption in transit:</b> TLS 1.2+ everywhere. HSTS with 1y max-age + preload + includeSubDomains in production.</div>
  <div class="fact"><b>Identity:</b> Ed25519 signing for every agent. Optional quantum-resistant hybrid (ML-DSA-65) via <code>quantum_did</code>.</div>
  <div class="fact"><b>Audit chain:</b> SHA-256 Merkle chain signed with Ed25519. Verify integrity at <a href="/v1/audit/verify" style="color:#818cf8">/v1/audit/verify</a>. Tamper-evident by design.</div>
  <div class="fact"><b>Backups:</b> Daily signed JSON bundles via <code>backup_restore</code>. SHA-256 digest on every backup. 30-day retention default; Enterprise gets configurable.</div>
  <div class="fact"><b>Secret management:</b> all third-party keys encrypted at rest, never logged, redacted in error messages. Rotation via <code>POST /v1/agents/:did/keys/:id/rotate</code>.</div>
</section>

<section>
  <h2>Data locality + retention</h2>
  <table>
    <thead><tr><th>Data class</th><th>Storage</th><th>Retention</th></tr></thead>
    <tbody>
      <tr><td>Audit chain</td><td>Postgres (Neon US-East default; EU/APAC on Enterprise)</td><td>Permanent (append-only)</td></tr>
      <tr><td>Inference call logs</td><td>Same region as audit chain</td><td>30 days default; Pro+ configurable</td></tr>
      <tr><td>KYC documents</td><td>S3 with KMS encryption, same region</td><td>7 years (regulatory requirement)</td></tr>
      <tr><td>Financial records</td><td>Same region as audit chain</td><td>7 years (US/EU law)</td></tr>
      <tr><td>API request bodies</td><td>Not stored beyond log line</td><td>Never persisted</td></tr>
      <tr><td>Webhook deliveries</td><td>Same region</td><td>90 days, then pruned</td></tr>
    </tbody>
  </table>
</section>

<section>
  <h2>Penetration testing + bug bounty</h2>
  <div class="fact"><b>Annual pentest</b> by an independent CREST/OSCP-certified firm. Latest scope: all public-facing routes + audit chain + bank_core. Report available under NDA to qualified prospects.</div>
  <div class="fact"><b>Bug bounty</b>: $500-$10K per finding via <a href="/security/disclosure" style="color:#818cf8">responsible disclosure</a>. Critical findings disclosed in <a href="/changelog" style="color:#818cf8">changelog</a>.</div>
  <div class="fact"><b>Continuous fuzzing</b>: route_smoke test runs every CI pass; 793 GET routes probed for 5xx. We also run weekly authenticated fuzz tests.</div>
</section>

<section>
  <h2>Subprocessor list</h2>
  <p style="color:#888;font-size:14px;margin-bottom:12px">Minimal — see <a href="/legal/subprocessors" style="color:#818cf8">/legal/subprocessors</a> for the live list. Every subprocessor is bound by DPA.</p>
  <table>
    <thead><tr><th>Subprocessor</th><th>Purpose</th><th>Data classes</th></tr></thead>
    <tbody>
      <tr><td>Neon</td><td>Postgres hosting</td><td>All operational data</td></tr>
      <tr><td>Vercel / AWS</td><td>Application hosting</td><td>Request/response transit only</td></tr>
      <tr><td>Stripe</td><td>Payment processing</td><td>Billing-only</td></tr>
      <tr><td>Anthropic / OpenAI / Google</td><td>LLM inference (opt-in routing)</td><td>Prompt content (transient)</td></tr>
    </tbody>
  </table>
</section>

<div class="actions">
  <a href="mailto:security@openheab.com?subject=SOC%202%20report%20request">Request SOC 2 report</a>
  <a class="secondary" href="/security/disclosure">Report a vulnerability</a>
  <a class="secondary" href="/legal/privacy">Privacy policy</a>
  <a class="secondary" href="/sla">SLA terms</a>
</div>

<div class="footer">
  <a href="/.well-known/security.txt">security.txt</a> · <a href="/v1/audit/verify">audit chain verify</a> · <a href="/status">live status</a>
</div>

</div></body></html>`;
}

const SLA_TIERS = [
  { plan: 'Free',       uptime: '99.0%',  rt_4xx: 'best effort', rt_5xx: 'best effort', credit: '0%', support: 'community' },
  { plan: 'Starter',    uptime: '99.5%',  rt_4xx: '24h',         rt_5xx: '24h',         credit: '5%',  support: 'email · 24h' },
  { plan: 'Pro',        uptime: '99.9%',  rt_4xx: '4h',          rt_5xx: '4h',          credit: '10%', support: 'priority email · 4h' },
  { plan: 'Team',       uptime: '99.95%', rt_4xx: '1h',          rt_5xx: '1h',          credit: '25%', support: 'Slack channel · 1h' },
  { plan: 'Enterprise', uptime: '99.99%', rt_4xx: '15min',       rt_5xx: '15min',       credit: '50%', support: 'dedicated CSM · 24/7 phone' }
];

function renderSlaPage() {
  return `<!doctype html><html><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>SLA — OpenHeab</title>
<meta name="description" content="Service Level Agreement terms per tier. Uptime targets, response times, credit schedule.">
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Inter', sans-serif; background: #0a0a0f; color: #e7e7ee; line-height: 1.6; }
.wrap { max-width: 880px; margin: 0 auto; padding: 48px 24px 80px; }
.nav { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; }
.nav .logo { font-weight: 700; font-size: 18px; color: #fff; text-decoration: none; }
.nav .links a { color: #888; margin-left: 20px; font-size: 14px; text-decoration: none; }
.nav .links a:hover { color: #fff; }
h1 { font-size: 36px; font-weight: 700; letter-spacing: -0.8px; margin-bottom: 10px; }
.subtitle { color: #888; font-size: 16px; margin-bottom: 36px; }
.meta { color: #666; font-size: 13px; margin-bottom: 24px; }
table { width: 100%; border-collapse: collapse; background: #14141c; border-radius: 10px; overflow: hidden; margin-bottom: 28px; }
th, td { padding: 12px 14px; text-align: left; font-size: 13px; border-bottom: 1px solid #1f1f2a; }
th { background: #1a1a25; color: #888; font-weight: 500; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
td.mono { font-family: monospace; }
td.right { text-align: right; }
section { margin: 36px 0; }
section h2 { font-size: 18px; margin-bottom: 12px; font-weight: 600; }
section p, section li { color: #c5c5d5; margin-bottom: 8px; font-size: 14px; }
section ul, section ol { padding-left: 22px; }
section code { background: #14141c; padding: 2px 6px; border-radius: 4px; font-size: 12px; }
.footer { color: #555; font-size: 13px; margin-top: 48px; text-align: center; }
.footer a { color: #888; margin: 0 8px; }
</style></head><body><div class="wrap">

<nav class="nav">
  <a class="logo" href="/">OpenHeab</a>
  <div class="links">
    <a href="/trust">Trust</a>
    <a href="/sla" style="color:#fff">SLA</a>
    <a href="/security/disclosure">Disclosure</a>
    <a href="/pricing">Pricing</a>
    <a href="/legal/terms">Terms</a>
  </div>
</nav>

<h1>Service Level Agreement</h1>
<p class="subtitle">Uptime, response times, and remedy schedule per subscription tier. SLA credits apply automatically against the next invoice.</p>
<p class="meta">Effective May 15, 2026 · Version 2.0</p>

<section>
  <h2>Coverage matrix</h2>
  <table>
    <thead>
      <tr>
        <th>Plan</th>
        <th>Monthly uptime</th>
        <th>Sev-1 response</th>
        <th>Other response</th>
        <th>Credit</th>
        <th>Support</th>
      </tr>
    </thead>
    <tbody>
${SLA_TIERS.map(t => `      <tr>
        <td><b>${escapeHtml(t.plan)}</b></td>
        <td class="mono">${escapeHtml(t.uptime)}</td>
        <td class="mono">${escapeHtml(t.rt_5xx)}</td>
        <td class="mono">${escapeHtml(t.rt_4xx)}</td>
        <td class="mono right">${escapeHtml(t.credit)}</td>
        <td>${escapeHtml(t.support)}</td>
      </tr>`).join('\n')}
    </tbody>
  </table>
</section>

<section>
  <h2>Uptime calculation</h2>
  <p>Monthly uptime % = (total minutes − unscheduled-downtime minutes) / total minutes × 100. Scheduled maintenance windows announced ≥7 days in advance on <a href="/status" style="color:#818cf8">/status</a> and via <a href="/status.rss" style="color:#818cf8">/status.rss</a> are excluded.</p>
  <p>"Downtime" = the substrate returns 5xx or fails to respond within 30 seconds on a healthy probe (<code>/v1/_health/deep</code>) for &gt;5 consecutive minutes.</p>
</section>

<section>
  <h2>Credit schedule</h2>
  <p>When monthly uptime falls below your tier's target, the credit % shown above is applied to your next invoice automatically:</p>
  <ul>
    <li>Pro tier with 99.85% uptime (vs 99.9% target) → 10% credit</li>
    <li>Team tier with 99.90% uptime (vs 99.95% target) → 25% credit</li>
    <li>Enterprise tier with 99.95% uptime (vs 99.99% target) → 50% credit</li>
  </ul>
  <p>Credits cap at one month's subscription fee. Multiple incidents in the same month don't stack beyond cap.</p>
</section>

<section>
  <h2>Severity definitions</h2>
  <ul>
    <li><b>Sev-1 (critical):</b> service unavailable or material data integrity issue. Examples: <code>/v1/_health/deep</code> returns red; audit chain verification fails; bank ledger drift &gt;$1.</li>
    <li><b>Sev-2 (high):</b> material functionality unavailable for a subset of customers. Examples: KYC provider down; specific primitive returning 5xx.</li>
    <li><b>Sev-3 (medium):</b> non-blocking bug; workaround exists.</li>
    <li><b>Sev-4 (low):</b> cosmetic, documentation, or feature request.</li>
  </ul>
</section>

<section>
  <h2>How to file a claim</h2>
  <ol>
    <li>Email <a href="mailto:sla@openheab.com" style="color:#818cf8">sla@openheab.com</a> within 30 days of the incident.</li>
    <li>Include: agent_did, time window, incident URL from <a href="/status" style="color:#818cf8">/status</a> (if any), brief impact statement.</li>
    <li>We respond within 5 business days; approved credits apply on the next invoice.</li>
  </ol>
</section>

<section>
  <h2>Exclusions</h2>
  <p>SLA does not apply to:</p>
  <ul>
    <li>Free tier (no SLA — best effort)</li>
    <li>Scheduled maintenance (announced ≥7d in advance)</li>
    <li>Force majeure (natural disasters, ISP outages outside our control, government action)</li>
    <li>Customer-induced issues (rate-limit exceeded, malformed requests, compromised credentials)</li>
    <li>Upstream LLM provider outages when you're using BYO-provider keys</li>
  </ul>
</section>

<div class="footer">
  Questions? <a href="mailto:sla@openheab.com">sla@openheab.com</a> · <a href="/status">Live status</a> · <a href="/legal/terms">Terms</a>
</div>

</div></body></html>`;
}

function renderDisclosurePage() {
  return `<!doctype html><html><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Security Disclosure — OpenHeab</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Inter', sans-serif; background: #0a0a0f; color: #e7e7ee; line-height: 1.6; }
.wrap { max-width: 720px; margin: 0 auto; padding: 48px 24px 80px; }
.nav { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; }
.nav .logo { font-weight: 700; font-size: 18px; color: #fff; text-decoration: none; }
.nav .links a { color: #888; margin-left: 20px; font-size: 14px; text-decoration: none; }
.nav .links a:hover { color: #fff; }
h1 { font-size: 36px; font-weight: 700; letter-spacing: -0.8px; margin-bottom: 10px; }
.subtitle { color: #888; font-size: 16px; margin-bottom: 36px; }
section { margin: 28px 0; }
section h2 { font-size: 18px; margin-bottom: 12px; font-weight: 600; }
section p, section li { color: #c5c5d5; margin-bottom: 8px; font-size: 14px; }
section ul, section ol { padding-left: 22px; }
section code { background: #14141c; padding: 2px 6px; border-radius: 4px; font-size: 12px; }
.bounty { background: #14141c; border-left: 3px solid #22c55e; padding: 16px 20px; border-radius: 4px; margin: 20px 0; }
.bounty b { color: #22c55e; }
.table { width: 100%; background: #14141c; border-radius: 8px; overflow: hidden; margin: 14px 0; }
.table td, .table th { padding: 10px 14px; text-align: left; border-bottom: 1px solid #1f1f2a; font-size: 13px; }
.table th { background: #1a1a25; color: #888; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
</style></head><body><div class="wrap">

<nav class="nav">
  <a class="logo" href="/">OpenHeab</a>
  <div class="links">
    <a href="/trust">Trust</a>
    <a href="/sla">SLA</a>
    <a href="/security/disclosure" style="color:#fff">Disclosure</a>
    <a href="/.well-known/security.txt">security.txt</a>
  </div>
</nav>

<h1>Responsible Security Disclosure</h1>
<p class="subtitle">Find a vulnerability? We pay you, fix it fast, and credit you in the changelog.</p>

<div class="bounty">
  <b>Bug bounty payouts:</b> $500 (low) · $1,500 (medium) · $5,000 (high) · $10,000 (critical). Paid in USDC or USD bank transfer within 14 days of triage.
</div>

<section>
  <h2>How to report</h2>
  <ol>
    <li>Email <a href="mailto:security@openheab.com" style="color:#818cf8">security@openheab.com</a> (PGP key in <code>/.well-known/openheab-pgp.asc</code> if you want to encrypt).</li>
    <li>Include: vulnerability class, affected route/endpoint, reproduction steps, observed impact, suggested fix (optional).</li>
    <li>We respond within 24 hours with an initial triage; full assessment within 5 business days.</li>
    <li>We coordinate disclosure timeline with you; standard is 90 days from report to public.</li>
    <li>Reward paid on confirmed fix.</li>
  </ol>
</section>

<section>
  <h2>Severity rubric</h2>
  <table class="table">
    <thead><tr><th>Severity</th><th>Examples</th><th>Payout</th></tr></thead>
    <tbody>
      <tr><td><b>Critical</b></td><td>Account takeover; audit chain forgery; sanctions screening bypass; private-key extraction</td><td>$10,000</td></tr>
      <tr><td><b>High</b></td><td>Auth bypass to admin; SQL injection; arbitrary file read; financial logic flaw</td><td>$5,000</td></tr>
      <tr><td><b>Medium</b></td><td>Stored XSS; CSRF on mutating endpoints; IDOR on resource access</td><td>$1,500</td></tr>
      <tr><td><b>Low</b></td><td>Reflected XSS; missing rate limit; verbose error leak; clickjacking</td><td>$500</td></tr>
    </tbody>
  </table>
</section>

<section>
  <h2>Out of scope</h2>
  <ul>
    <li>Self-XSS, XSS that only fires for the reporter</li>
    <li>Vulnerabilities in third-party services we route to (report directly to them)</li>
    <li>Findings requiring physical access, social engineering, or non-public infrastructure</li>
    <li>Theoretical vulnerabilities without working PoC</li>
    <li>Volumetric DoS (just don't)</li>
    <li>Spam / scraping rate limits (we know)</li>
  </ul>
</section>

<section>
  <h2>Safe harbor</h2>
  <p>If you act in good faith — accessing only your own account, avoiding privacy violations, not destroying data, not disrupting service — we won't pursue legal action. We agree not to file complaint with law enforcement against you, and to defend you against third-party legal claims arising from your good-faith research.</p>
</section>

<section>
  <h2>Hall of fame</h2>
  <p>Researchers who've reported confirmed vulnerabilities. Email us to opt in or stay anonymous.</p>
  <p style="color:#666;font-style:italic;font-size:13px">No public reports yet — be the first.</p>
</section>

</div></body></html>`;
}

function registerEnterpriseAssuranceRoutes(app, pool) {
  const express = require('express');

  app.get('/trust', (req, res) => {
    res.set('content-type', 'text/html; charset=utf-8');
    res.set('cache-control', 'public, max-age=3600');
    res.send(renderTrustPage());
  });

  app.get('/sla', (req, res) => {
    res.set('content-type', 'text/html; charset=utf-8');
    res.set('cache-control', 'public, max-age=3600');
    res.send(renderSlaPage());
  });
  app.get('/sla.json', (req, res) => res.json({ tiers: SLA_TIERS, effective: '2026-05-15', version: '2.0' }));

  app.get('/security/disclosure', (req, res) => {
    res.set('content-type', 'text/html; charset=utf-8');
    res.set('cache-control', 'public, max-age=3600');
    res.send(renderDisclosurePage());
  });

  // GET /v1/me/invoices — list invoices for the agent's org
  app.get('/v1/me/invoices', async (req, res) => {
    const ctx = await resolveAgent(pool, req);
    if (!ctx) return res.status(401).json({ error: 'unauthenticated' });
    const r = await pool.query(`
      SELECT i.invoice_id, i.org_id, i.period_start, i.period_end, i.subtotal_cents,
             i.tax_cents, i.total_cents, i.status, i.created_at
      FROM invoices i JOIN org_members om ON om.org_id = i.org_id
      WHERE om.agent_did=$1 ORDER BY i.created_at DESC LIMIT 50
    `, [ctx.did]).catch(() => ({ rows: [] }));
    res.set('cache-control', 'private, no-store');
    res.json({ did: ctx.did, invoices: r.rows });
  });

  // GET /v1/me/billing/usage — current billing period usage broken down
  app.get('/v1/me/billing/usage', async (req, res) => {
    const ctx = await resolveAgent(pool, req);
    if (!ctx) return res.status(401).json({ error: 'unauthenticated' });
    // Current month boundary
    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();
    const safe = async (sql, params) => {
      try { return (await pool.query(sql, params)).rows; } catch { return []; }
    };
    const inference = await safe(`
      SELECT provider, COUNT(*)::int AS calls,
             COALESCE(SUM(prompt_tokens),0)::bigint AS prompt_tokens,
             COALESCE(SUM(completion_tokens),0)::bigint AS completion_tokens,
             COALESCE(SUM(cost_cents),0)::bigint AS cost_cents
      FROM inference_calls WHERE agent_did=$1 AND created_at >= $2
      GROUP BY provider ORDER BY cost_cents DESC
    `, [ctx.did, monthStart]);
    const totals = inference.reduce((acc, row) => ({
      calls: acc.calls + Number(row.calls || 0),
      prompt_tokens: acc.prompt_tokens + Number(row.prompt_tokens || 0),
      completion_tokens: acc.completion_tokens + Number(row.completion_tokens || 0),
      cost_cents: acc.cost_cents + Number(row.cost_cents || 0)
    }), { calls: 0, prompt_tokens: 0, completion_tokens: 0, cost_cents: 0 });
    res.set('cache-control', 'private, no-store');
    res.json({
      did: ctx.did,
      period_start: monthStart,
      period_end: new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString(),
      totals,
      by_provider: inference
    });
  });
}

module.exports = { migrate, registerEnterpriseAssuranceRoutes, SLA_TIERS };
